CAR_UTTERANCES = [
    "car",
    "vehicle",
    "engine",
    "speed",
    "drive",
    "wheels",
    "fuel",
    "horsepower",
    "brake",
    "race",
    "ratings",
    "manufacture",
    "steering wheel",
    "dashboard",
    "acceleration",
    "sales",
    "production",
    "kilometer"
    # "fuel sales vehicle speed",
    # "sales ratings engine horsepower",
    # "brake steering wheel manufacture acceleration",
    # "race brake vehicle engine",
    # "fuel sales acceleration brake",
    # "acceleration kilometer brake sales",
    # "dashboard fuel wheels car",
    # "vehicle manufacture drive horsepower",
    # "ratings dashboard vehicle production",
    # "race kilometer drive vehicle",
    # "drive car engine speed",
    # "production manufacture vehicle wheels",
    # "fuel race horsepower speed",
    # "ratings steering wheel race acceleration",
    # "drive manufacture speed kilometer",
    # "brake acceleration dashboard manufacture",
    # "steering wheel vehicle manufacture kilometer",
    # "manufacture car horsepower wheels",
    # "race fuel speed brake",
    # "car dashboard fuel sales",
    # "manufacture production race speed",
    # "brake manufacture acceleration drive",
    # "steering wheel brake fuel ratings",
    # "steering wheel drive dashboard production",
    # "car speed sales race",
    # "ratings steering wheel sales manufacture",
    # "fuel drive acceleration brake",
    # "drive ratings engine speed",
    # "wheels drive vehicle acceleration",
    # "dashboard sales manufacture acceleration",
]

COUNTRIES_UTTERANCES = [
    "land",
    "nation",
    "country",
    "homeland",
    "flag",
    "borders",
    "culture",
    "history",
    "cuisine",
    "traditions",
    "rivers",
    "cities",
    "passport",
    "landscape",
    "mountains",
    "fauna", 
    "flora",
    "government",
    "capital",
    "citizen",
    "language",
    "economy",
    "currency",
    "anthem",
    "constitution"
    "population",
    "forest",
    "desert",
    "coastline",
    "military",
    "politics",
    "province",
    # "flag province cities coastline",
    # "land traditions fauna citizen",
    # "fauna anthem homeland cuisine",
    # "military nation flora borders",
    # "flag military forest coastline",
    # "mountains culture currency rivers",
    # "cities desert capital politics",
    # "flora culture government homeland",
    # "anthem land flag culture",
    # "military culture currency cuisine",
    # "flora cities coastline anthem",
    # "province flora citizen land",
    # "nation country currency coastline",
    # "province flora mountains desert",
    # "language cities flag constitutionpopulation",
    # "government military homeland flora",
    # "politics flora mountains capital",
    # "constitutionpopulation economy anthem currency",
    # "country nation anthem traditions",
    # "fauna coastline province culture",
    # "flag currency fauna military",
    # "economy culture politics cities",
    # "province currency desert land",
    # "flora traditions cuisine passport",
    # "passport homeland anthem capital",
    # "economy citizen capital cuisine",
    # "forest anthem capital country",
    # "nation country forest anthem",
    # "citizen cuisine coastline history",
    # "history language economy culture"
]
